;;; acp-fakes.el --- A fake agent shell -*- lexical-binding: t; -*-


;;; Commentary:
;;

;;; Code:

(require 'acp-fakes)

(defun acp-fakes-load-session ()
  "Load and replay a traffic session from file."
  (interactive)
  (let* ((traffic-file (read-file-name "Load traffic file: " nil nil t))
         (messages (acp-traffic-read-file traffic-file))
         (buffer (acp-fakes-start-agent messages))
         (first-prompt (progn
                         (unless buffer
                           (error "No shell buffer available"))
                         (seq-find (lambda (item)
                                     (and (eq (map-elt item :direction) 'outgoing)
                                          (equal (map-nested-elt item '(:object method)) "session/prompt")
                                          (let ((text (map-nested-elt item '(:object params prompt 0 text))))
                                            (and text (not (string-empty-p text))))))
                                   messages)))
         (first-prompt-text (map-nested-elt first-prompt '(:object params prompt 0 text))))
    (unless first-prompt-text
      (error "No first prompt text available to kick replay off"))
    (with-current-buffer buffer
      (shell-maker-submit :input first-prompt-text))))

(defun acp-fakes-start-agent (messages)
  "Start a fake agent with traffic MESSAGES."
  (let* ((authenticate-message (acp-fakes--get-authenticate-request :messages messages))
         (authenticate-request (when authenticate-message
                                 (list (cons :method (map-nested-elt authenticate-message '(:object method)))
                                       (cons :params (map-nested-elt authenticate-message '(:object params))))))
         (config (acp-make-agent-config
                  :mode-line-name "Fake"
                  :buffer-name "Fake"
                  :shell-prompt "Fake> "
                  :shell-prompt-regexp "Fake> "
                  :icon-name "https://purepng.com/public/uploads/large/purepng.com-futurama-benderfuturamaanimated-sciencefictionsitcomcartoonfuturama-benderbender-17015285631369sm6z.png"
                  :welcome-function #'acp-fakes---welcome-message
                  :client-maker (lambda (buffer)
                                  (let ((client (acp-fakes-make-client messages)))
                                    (map-put! client :context-buffer buffer)
                                    client))
                  :needs-authentication authenticate-request
                  :authenticate-request-maker (lambda ()
                                                authenticate-request)))
         (buffer (acp--start :config config)))
    buffer))

(defun acp-fakes---welcome-message (config)
  "Return Fake ASCII art as per own repo using `shell-maker' CONFIG."
  (let ((art (acp--indent-string 4 (acp-fakes--ascii-art)))
        (message (string-trim-left (shell-maker-welcome-message config) "\n")))
    (concat "\n\n"
            art
            "\n\n"
            message)))

(defun acp-fakes--ascii-art ()
  "Fake ASCII art.

Generated by https://github.com/shinshin86/oh-my-logo."
  (let* ((is-dark (eq (frame-parameter nil 'background-mode) 'dark))
         (text (string-trim "
░▒▓████████▓▒░▒▓██████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░
░▒▓█▓▒░     ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░
░▒▓█▓▒░     ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░
░▒▓██████▓▒░░▒▓████████▓▒░▒▓███████▓▒░░▒▓██████▓▒░
░▒▓█▓▒░     ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░
░▒▓█▓▒░     ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░
░▒▓█▓▒░     ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░
" "\n")))
    (propertize text 'font-lock-face (if is-dark
                                         '(:foreground "#b7c3cc" :inherit fixed-pitch)
                                       '(:foreground "#7e909a" :inherit fixed-pitch)))))



(provide 'acp-fakes)

;;; acp-fakes.el ends here
